#+title: PWN Redux

A web fiction platform for authors and readers, built with [[https://biffweb.com][Biff]]. PWN is not ready for general use yet. When it is, the primary instance will be hosted at [[https://projectwebnovel.com][Project Web Novel]].

* Getting started
** Prerequisites
For development, PWN requires Java, Clojure, and Babashka to be installed on the host machine. You must also have a =config.edn= file in the project root that looks something like this:

#+begin_src clojure
;; vim: ft=clojure
{:prod {:biff.xtdb/dir "storage/xtdb"
        :biff.xtdb/topology :standalone
        ;; Standalone topology in production isn't recommended for anything
        ;; serious. You can uncomment the following to use managed postgres
        ;; instead.
        ;; :biff.xtdb/topology :jdbc
        ;; :biff.xtdb.jdbc/jdbcUrl "postgresql://user:password@host:port/dbname?sslmode=require"
        :biff/base-url "https://example.com"
        ;; Postmark is used to send email sign-in links. Create an account at
        ;; https://postmarkapp.com
        :postmark/api-key nil
        ;; Change to the address of your sending identity. Set a reply-to
        ;; address on your sending identity if you want to receive replies and
        ;; your from address isn't configured for receiving.
        :postmark/from "hello@example.com"
        ;; Recaptcha is used to protect your sign-in page. Go to
        ;; https://www.google.com/recaptcha/about/ and add a site. Select v2
        ;; invisible. Add localhost to your list of allowed domains.
        :recaptcha/site-key nil
        :recaptcha/secret-key nil
        :biff.middleware/cookie-secret <your-cookie-secret>
        :biff/jwt-secret <your-jwt-secret>}
 :dev {:merge [:prod]
       :pwn/enable-beholder true
       :biff/host "0.0.0.0"
       :biff/port 8080
       :biff/base-url "http://localhost:8080"
       :biff.xtdb/topology :standalone
       :biff.middleware/secure false}
 :tasks {;; Set this if the auto-detection doesn't work
         ;; Possible values: macos-x64, macos-arm64, linux-x64, linux-arm64
         :biff.tasks/tailwind-build nil
         :biff.tasks/main-ns pwn
         :biff.tasks/soft-deploy-fn pwn/on-save
         :biff.tasks/deploy-from "master"
         :biff.tasks/deploy-to "prod"
         :biff.tasks/server "example.com"}}

#+end_src

** Running in Development
In a shell, you can then run =bb dev= in the project root to get started. The application will then be available at =https://localhost:8080=. Files will be hot-reloaded upon change.

To connect to the running REPL with Emacs, run =M-x cider-connect-clj= (or =SPC m c= for Doom users), and select =localhost= followed by =pwn:7888=.

* Contributing
As this project is in pre-release, we are keeping development in-house at this time. Please look forward to future contributing guidelines as the project matures.
